server:
  hostname: 127.0.0.1
  port: 2002
  trustProxy:
    - loopback
services:
  database:
    type: mariadb
    host: 127.0.0.1
    port: 3306
    username: syzoj-ng
    password: syzoj-ng
    database: syzoj-ng
  minio:
    endPoint: syzoj-ng.test
    port: 9000
    useSSL: false
    accessKey: minioadmin
    secretKey: minioadmin
    bucket: syzoj-ng-files
  redis: redis://127.0.0.1:6379
  mail:
    address: no-reply@syzoj-ng.test
    transport: smtp://username:password@syzoj-ng-smtp.test:25
security:
  crossOrigin:
    enabled: true
    whiteList:
      - http://syzoj-ng-app.test
  sessionSecret: don't leak this
  maintainceKey: also don't leak this
preference:
  siteName: SYZOJ NG
  security:
    requireEmailVerification: true
    allowUserChangeUsername: true
    allowEveryoneCreateProblem: true
    allowNonAdminEditPublicProblem: true
    allowOwnerManageProblemPermission: false
    allowOwnerDeleteProblem: true
  pagination:
    problemSet: 50
    searchProblemsPreview: 7
    submissions: 10
    submissionStatistics: 10
    userList: 30
    userAuditLogs: 10
resourceLimit:
  problemTestdataFiles: 40
  problemTestdataSize: 134217728
  problemAdditionalFileFiles: 40
  problemAdditionalFileSize: 134217728
  problemTestcases: 20
  problemTimeLimit: 2000
  problemMemoryLimit: 512
  submissionFileSize: 10485760
queryLimit:
  problemSet: 100
  submissions: 10
  submissionStatistics: 10
  searchUser: 10
  searchGroup: 10
  userList: 100
  userAuditLogs: 20
vendor:
  ip2region: /opt/ip2region/ip2region.db
